In [23]:
import numpy as np
import pandas as pd

In [24]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [25]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [26]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [27]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\keras\src\layers\core\dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.get_weights()

[array([[ 0.23447323,  0.36194456],
        [-0.93837714, -0.7537551 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.7099589 ],
        [-0.62300086]], dtype=float32),
 array([0.], dtype=float32)]

In [30]:
new_weights= [np.array([[0.1, 0.1],
                      [0.1, 0.1]], dtype=np.float32),
             np.array([0., 0.], dtype=np.float32),
             np.array([[0.1],
                       [0.1]], dtype=np.float32),
              np.array([0.], dtype=np.float32)]

In [31]:
model.set_weights(new_weights)

In [32]:
optimizer= keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [34]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 27.8902 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.5685 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.2387 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.8991 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.5493 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.1890 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 25.8177
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.4356 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.0423 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.6381 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 24.2230 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.7971 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.3608 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.9143 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.4580 
Epoch 16/75
4/4 ━━

In [36]:
model.get_weights()

[array([[0.3733851 , 0.3733851 ],
        [0.36585993, 0.36585993]], dtype=float32),
 array([0.27228436, 0.27228436], dtype=float32),
 array([[0.37296107],
        [0.37296107]], dtype=float32),
 array([0.2048301], dtype=float32)]